package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"fmt"
	"zurvan-api/feature/auth/domain/models"
	"zurvan-api/graph/model"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthResponse, error) {
	userInput := &models.UserInput{
		Name:     input.Name,
		Email:    input.Email,
		Password: input.Password,
	}

	authResponse, err := r.AuthUseCase.Register(ctx, userInput)
	if err != nil {
		return nil, err
	}

	return &model.AuthResponse{
		User: &model.User{
			ID:          authResponse.User.ID.String(),
			Name:        authResponse.User.Name,
			Email:       authResponse.User.Email,
			IsVerified:  authResponse.User.IsVerified,
			CreatedAt:   authResponse.User.CreatedAt,
			UpdatedAt:   authResponse.User.UpdatedAt,
			LastLoginAt: authResponse.User.LastLoginAt,
		},
		AccessToken:  authResponse.AccessToken,
		RefreshToken: authResponse.RefreshToken,
		ExpiresIn:    int(authResponse.ExpiresIn),
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthResponse, error) {
	loginInput := &models.LoginInput{
		Email:    input.Email,
		Password: input.Password,
	}

	authResponse, err := r.AuthUseCase.Login(ctx, loginInput)
	if err != nil {
		return nil, err
	}

	return &model.AuthResponse{
		User: &model.User{
			ID:          authResponse.User.ID.String(),
			Name:        authResponse.User.Name,
			Email:       authResponse.User.Email,
			IsVerified:  authResponse.User.IsVerified,
			CreatedAt:   authResponse.User.CreatedAt,
			UpdatedAt:   authResponse.User.UpdatedAt,
			LastLoginAt: authResponse.User.LastLoginAt,
		},
		AccessToken:  authResponse.AccessToken,
		RefreshToken: authResponse.RefreshToken,
		ExpiresIn:    int(authResponse.ExpiresIn),
	}, nil
}

// VerifyEmail is the resolver for the verifyEmail field.
func (r *mutationResolver) VerifyEmail(ctx context.Context, input model.VerifyEmailInput) (string, error) {
	// Extract JWT token from context and get user ID
	token, err := extractTokenFromContext(ctx)
	if err != nil {
		return "", fmt.Errorf("authentication required: %w", err)
	}

	// Get user information from token
	user, err := r.AuthUseCase.GetUserFromToken(ctx, token)
	if err != nil {
		return "", fmt.Errorf("authentication failed: %w", err)
	}

	// Prepare verification input
	verifyInput := &models.EmailVerificationInput{
		Code: input.Code,
	}

	err = r.AuthUseCase.VerifyEmail(ctx, user.ID, verifyInput)
	if err != nil {
		return "", err
	}

	return "Email verified successfully.", nil
}

// ResendVerificationCode is the resolver for the resendVerificationCode field.
func (r *mutationResolver) ResendVerificationCode(ctx context.Context, input model.ResendVerificationInput) (string, error) {
	// Extract JWT token from context and get user ID
	token, err := extractTokenFromContext(ctx)
	if err != nil {
		return "", fmt.Errorf("authentication required: %w", err)
	}

	// Get user information from token
	user, err := r.AuthUseCase.GetUserFromToken(ctx, token)
	if err != nil {
		return "", fmt.Errorf("authentication failed: %w", err)
	}

	// Prepare resend input (empty struct)
	resendInput := &models.ResendVerificationInput{}

	err = r.AuthUseCase.ResendVerificationCode(ctx, user.ID, resendInput)
	if err != nil {
		return "", err
	}

	return "Verification code sent successfully.", nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, input model.RefreshTokenInput) (*model.AuthResponse, error) {
	authResponse, err := r.AuthUseCase.RefreshToken(ctx, input.RefreshToken)
	if err != nil {
		return nil, err
	}

	return &model.AuthResponse{
		User: &model.User{
			ID:          authResponse.User.ID.String(),
			Name:        authResponse.User.Name,
			Email:       authResponse.User.Email,
			IsVerified:  authResponse.User.IsVerified,
			CreatedAt:   authResponse.User.CreatedAt,
			UpdatedAt:   authResponse.User.UpdatedAt,
			LastLoginAt: authResponse.User.LastLoginAt,
		},
		AccessToken:  authResponse.AccessToken,
		RefreshToken: authResponse.RefreshToken,
		ExpiresIn:    int(authResponse.ExpiresIn),
	}, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	// Extract JWT token from context
	token, err := extractTokenFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %w", err)
	}

	// Get user information from token
	user, err := r.AuthUseCase.GetUserFromToken(ctx, token)
	if err != nil {
		return nil, fmt.Errorf("authentication failed: %w", err)
	}

	// Convert to GraphQL model
	return &model.User{
		ID:          user.ID.String(),
		Name:        user.Name,
		Email:       user.Email,
		IsVerified:  user.IsVerified,
		CreatedAt:   user.CreatedAt,
		UpdatedAt:   user.UpdatedAt,
		LastLoginAt: user.LastLoginAt,
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
